services:
  - type: web
    name: pathfinder-laravel-backend
    env: docker
    plan: free
    rootDir: backend
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://your-backend.onrender.com